import React from 'react';
import { colors, iconSizes } from '@/theme';
import {
  Home,
  Cloud,
  CalendarDays,
  User,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  X,
  Search,
  Bell,
  BellOff,
  Settings,
  CreditCard,
  Ticket,
  Plane,
  MapPin,
  Clock,
  AlertTriangle,
  Shield,
  Trophy,
  BookOpen,
  Camera,
  QrCode,
  Wallet,
  MessageCircle,
  MessageSquare,
  Users,
  Plus,
  Minus,
  Check,
  Eye,
  EyeOff,
  Upload,
  Download,
  RefreshCw,
  Filter,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Trash2,
  Heart,
  Share2,
  Star,
  Zap,
  Wind,
  Thermometer,
  Droplets,
  Sun,
  CloudRain,
  Siren,
  ClipboardList,
  Clipboard,
  FolderOpen,
  BarChart3,
  History,
  LogOut,
  Lock,
  Fingerprint,
  Smartphone,
  Globe,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowDownRight,
  ArrowDownLeft,
  Info,
  HelpCircle,
  ExternalLink,
  Copy,
  Send,
  Briefcase,
  GraduationCap,
  Building2,
  Bed,
  ShoppingBag,
  Package,
  CircleCheck,
  CircleX,
  Mail,
  ScanLine,
  LogIn,
  UserPlus,
  TrendingUp,
  Award,
  FileText,
  PenTool,
  AlertCircle,
  Image as ImageIcon,
  Keyboard,
  Target,
  Hash,
  Phone,
  Cpu,
  HardHat,
  Gauge,
  Shirt,
  Calculator,
  SlidersHorizontal,
  Pill,
  Wrench,
  Flame,
  PlusCircle,
  LayoutGrid,
  Compass,
  CloudLightning,
  Crosshair,
  CloudOff,
  Activity,
  Link2,
  File,
  Megaphone,
  List,
  RotateCcw,
  type LucideIcon,
} from 'lucide-react-native';

export type IconName =
  | 'home' | 'cloud' | 'calendar' | 'user' | 'chevron-left' | 'chevron-right'
  | 'chevron-down' | 'x' | 'search' | 'bell' | 'bell-off' | 'settings' | 'credit-card'
  | 'ticket' | 'plane' | 'map-pin' | 'clock' | 'alert-triangle' | 'shield'
  | 'trophy' | 'book-open' | 'camera' | 'qr-code' | 'wallet' | 'message-circle'
  | 'message-square' | 'users' | 'plus' | 'minus' | 'check' | 'eye' | 'eye-off' | 'upload'
  | 'download' | 'refresh' | 'filter' | 'more-horizontal' | 'more-vertical'
  | 'edit' | 'trash' | 'heart' | 'share' | 'star' | 'zap' | 'wind'
  | 'thermometer' | 'droplets' | 'sun' | 'cloud-rain' | 'siren'
  | 'clipboard-list' | 'clipboard' | 'folder-open' | 'bar-chart' | 'history' | 'log-out'
  | 'lock' | 'fingerprint' | 'smartphone' | 'globe' | 'arrow-up' | 'arrow-down'
  | 'arrow-left' | 'arrow-right' | 'arrow-up-right' | 'arrow-up-left' | 'arrow-down-right' | 'arrow-down-left'
  | 'info' | 'help-circle' | 'external-link'
  | 'copy' | 'send' | 'briefcase' | 'graduation-cap' | 'building' | 'bed'
  | 'shopping-bag' | 'package'
  | 'check-circle' | 'x-circle' | 'mail' | 'scan' | 'log-in' | 'user-plus'
  | 'trending-up' | 'award' | 'file-text' | 'pen-tool' | 'alert-circle' | 'image'
  | 'keyboard' | 'target' | 'hash' | 'phone' | 'cpu' | 'hard-hat' | 'gauge' | 'shirt'
  | 'calculator' | 'sliders' | 'pill' | 'wrench' | 'flame' | 'plus-circle'
  | 'grid' | 'compass' | 'cloud-lightning' | 'crosshair' | 'cloud-off' | 'activity'
  | 'link' | 'file' | 'tool'
  | 'megaphone' | 'list' | 'rotate-ccw';

const iconMap: Record<IconName, LucideIcon> = {
  'home': Home,
  'cloud': Cloud,
  'calendar': CalendarDays,
  'user': User,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'x': X,
  'search': Search,
  'bell': Bell,
  'bell-off': BellOff,
  'settings': Settings,
  'credit-card': CreditCard,
  'ticket': Ticket,
  'plane': Plane,
  'map-pin': MapPin,
  'clock': Clock,
  'alert-triangle': AlertTriangle,
  'shield': Shield,
  'trophy': Trophy,
  'book-open': BookOpen,
  'camera': Camera,
  'qr-code': QrCode,
  'wallet': Wallet,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'users': Users,
  'plus': Plus,
  'minus': Minus,
  'check': Check,
  'eye': Eye,
  'eye-off': EyeOff,
  'upload': Upload,
  'download': Download,
  'refresh': RefreshCw,
  'filter': Filter,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'edit': Edit,
  'trash': Trash2,
  'heart': Heart,
  'share': Share2,
  'star': Star,
  'zap': Zap,
  'wind': Wind,
  'thermometer': Thermometer,
  'droplets': Droplets,
  'sun': Sun,
  'cloud-rain': CloudRain,
  'siren': Siren,
  'clipboard-list': ClipboardList,
  'clipboard': Clipboard,
  'folder-open': FolderOpen,
  'bar-chart': BarChart3,
  'history': History,
  'log-out': LogOut,
  'lock': Lock,
  'fingerprint': Fingerprint,
  'smartphone': Smartphone,
  'globe': Globe,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-up-left': ArrowUpLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-down-left': ArrowDownLeft,
  'info': Info,
  'help-circle': HelpCircle,
  'external-link': ExternalLink,
  'copy': Copy,
  'send': Send,
  'briefcase': Briefcase,
  'graduation-cap': GraduationCap,
  'building': Building2,
  'bed': Bed,
  'shopping-bag': ShoppingBag,
  'package': Package,
  'check-circle': CircleCheck,
  'x-circle': CircleX,
  'mail': Mail,
  'scan': ScanLine,
  'log-in': LogIn,
  'user-plus': UserPlus,
  'trending-up': TrendingUp,
  'award': Award,
  'file-text': FileText,
  'pen-tool': PenTool,
  'alert-circle': AlertCircle,
  'image': ImageIcon,
  'keyboard': Keyboard,
  'target': Target,
  'hash': Hash,
  'phone': Phone,
  'cpu': Cpu,
  'hard-hat': HardHat,
  'gauge': Gauge,
  'shirt': Shirt,
  'calculator': Calculator,
  'sliders': SlidersHorizontal,
  'pill': Pill,
  'wrench': Wrench,
  'flame': Flame,
  'plus-circle': PlusCircle,
  'grid': LayoutGrid,
  'compass': Compass,
  'cloud-lightning': CloudLightning,
  'crosshair': Crosshair,
  'cloud-off': CloudOff,
  'activity': Activity,
  'link': Link2,
  'file': File,
  'tool': Wrench,
  'megaphone': Megaphone,
  'list': List,
  'rotate-ccw': RotateCcw,
};

export type SLIconSize = keyof typeof iconSizes;

interface SLIconProps {
  name: IconName;
  size?: SLIconSize;
  color?: string;
  strokeWidth?: number;
}

export default function SLIcon({
  name,
  size = 'md',
  color = colors.text.primary,
  strokeWidth = 2,
}: SLIconProps) {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null;

  return (
    <IconComponent
      size={iconSizes[size]}
      color={color}
      strokeWidth={strokeWidth}
    />
  );
}
